// Generated by CoffeeScript 1.8.0
(function() {
  var $;

  $ = jQuery;

  $(function() {
    $("#num-boosters").focus();
    return $("#num-boosters").keypress(function(e) {
      var count;
      if (e.which === 13) {
        count = $("#num-boosters").val();
        return $.get("http://127.0.0.1:5000/boosters?count=" + count, function(data) {
          var s, _i, _len, _results;
          data = data.replace("{", "").replace("}", "").replace(/"/g, "").split(", ");
          _results = [];
          for (_i = 0, _len = data.length; _i < _len; _i++) {
            s = data[_i];
            _results.push(console.log(s.split(":")));
          }
          return _results;
        });
      }
    });
  });

}).call(this);
