// Generated by CoffeeScript 1.8.0
(function() {
  var $;

  $ = jQuery;

  $(function() {
    console.log("foo");
    console.log($("#cards"));
    $.ajax;
    $("#cards").autocomplete({
      source: ['test', 'foo']
    });
    return console.log("foo");
  });

}).call(this);
